### ISSUE TITLE
Create a branch named centos

### ISSUE THREAD

**Issue by jcfr** [thewtex/docker-opengl#4]
Waiting we finalize the integration of updated X11 with the image based of centos, I suggest we maintain a branch named `centos-2016.10.20`

This will allow us to publish an image named `thewtex/opengl:centos-2016.10.20` that will be used for Slicer CI.

Ultimately, we will address the remain issues related to update of X11 and get rid of the debian based on .

Cc: @MayeulChassagnard

**Comment by MayeulChassagnard** [comment]
Done.

> Pull request reference: #1

**Comment by thewtex** [comment]
I've created a branch named `centos`. We can make centos PR's against this branch.

Before merging `centos` to `master`, we should add MicroBadger / revision labels / tagged versions of the Debian image so folks can still get access to the old version.
